### ISSUE TITLE
ident.me classified as IPv6; does both IPv4 and IPv6

### ISSUE THREAD

**Issue by pcarrier** [asweigart/whatismyip#1]
I see you've put https://ident.me in `IP6_WEBSITES`; it'd probably be better suited for `IP_WEBSITES`.

There are https://v4.ident.me and https://v6.ident.me (and their counterparts https://v4.tnedi.me and https://v6.tnedi.me for redundancy) that would be better suited for IP4_WEBSITES and IP6_WEBSITES respectively; more infos at https://api.ident.me

Thanks for the lib :)

**Comment by asweigart** [comment]
Fixed in 2024.2.20. Thank you so much!
